/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jjkoktnibeucqwsutqfm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqa29rdG5pYmV1Y3F3c3V0cWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3MDc1ODgsImV4cCI6MjA4MDI4MzU4OH0.ypeivzT5C_JoS9-UH1nrqVifjK4qD0HSTVd72_ldNLU"
